// The jsx graph was auto-generated by: https://github.com/pmndrs/gltfjsx
import * as THREE from 'three'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import { gsap } from 'gsap'

const DemoComputer = ({ props, seletedProjectIndex }) => {

    const videoLink = `/textures/project/project${seletedProjectIndex + 1}.mp4`

    const txt = useVideoTexture(videoLink);
    txt.flipY = false;

    const group = useRef()
    const { nodes, materials } = useGLTF('/mac-draco.glb')
    useFrame((state) => {
        const t = state.clock.getElapsedTime()
        group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.cos(t / 2) / 20 + 0.25, 0.1)
        group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(t / 4) / 20, 0.1)
        group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, Math.sin(t / 8) / 20, 0.1)
        group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, (-2 + Math.sin(t / 2)) / 2, 0.1)
    })

    useGSAP(() => {
        gsap.from(group.current.rotation, {
            y: Math.PI / 2,
            duration: 1,
            ease: 'power3.out'
        })
    }, [txt])

    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation-x={-0.425} position={[0, -0.04, 0.41]}>
                <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh material={materials.aluminium} geometry={nodes['Cube008'].geometry} />
                    <mesh material={materials['matte.001']} geometry={nodes['Cube008_1'].geometry} />
                    <mesh geometry={nodes['Cube008_2'].geometry}>
                        <meshBasicMaterial map={txt} />
                    </mesh>
                </group>
            </group>
            <mesh material={materials.keys} geometry={nodes.keyboard.geometry} position={[1.79, 0, 3.45]} />
            <group position={[0, -0.1, 3.39]}>
                <mesh material={materials.aluminium} geometry={nodes['Cube002'].geometry} />
                <mesh material={materials.trackpad} geometry={nodes['Cube002_1'].geometry} />
            </group>
            <mesh material={materials.touchbar} geometry={nodes.touchbar.geometry} position={[0, -0.03, 1.2]} />
        </group>
    )
}

export default DemoComputer


{/* Drei's HTML component can "hide behind" canvas geometry */ }
{/* <Html
                            rotation-x={-Math.PI / 2}
                            position={[-0.55, 0.1, 0.1]} // Adjust Y and Z to match screen center
                            scale={[0.58, 0.56, 1]} // Scale X and Y to match the screen size (adjust as needed)
                            transform
                            occlude
                        >
                            <div
                                onPointerDown={(e) => e.stopPropagation()}
                                style={{
                                    width: '100%',
                                    height: '100%',
                                    overflow: 'hidden',
                                    display: 'flex',
                                    justifyContent: 'center',
                                    alignItems: 'center',
                                    background: 'black',
                                }}
                            >
                                <video
                                    src={videoLink}
                                    muted
                                    autoPlay
                                    loop
                                    playsInline
                                    className='w-full h-full object-cover rounded-lg'
                                />
                            </div>
                        </Html> */}